In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('ESPORTISTAS_MOD7.csv', delimiter=';')
df.head()

              Atleta   Esporte  Ganhos_Totais
0       Lionel Messi   Futebol            639
1       Lebron James  Basquete            595
2  Cristiano Ronaldo   Futebol            565
3          Neymar Jr   Futebol            467
4      Stephen Curry  Basquete            452

In [3]:
df.groupby('Esporte')['Atleta'].count().reset_index().sort_values(by='Atleta', ascending=False)

             Esporte  Atleta
1           Basquete       8
5  Futebol Americano       7
4            Futebol       3
3               Boxe       2
7              Tenis       2
0      Automobilismo       1
2           Beisebol       1
6              Golfe       1

In [5]:
contagem = df['Esporte'].value_counts(normalize=True).reset_index()
contagem

             Esporte  proportion
0           Basquete        0.32
1  Futebol Americano        0.28
2            Futebol        0.12
3              Tenis        0.08
4               Boxe        0.08
5              Golfe        0.04
6      Automobilismo        0.04
7           Beisebol        0.04

## Média

In [6]:
soma_ganhos_totais = df['Ganhos_Totais'].sum()
quantidade_registros = len(df['Ganhos_Totais'])
media_ganhos_totais = soma_ganhos_totais / quantidade_registros
print('Média de Ganhos Totais: ', media_ganhos_totais)

Média de Ganhos Totais:  377.0

In [7]:
df['Ganhos_Totais'].mean()

np.float64(377.0)

In [8]:
df.groupby('Esporte')['Ganhos_Totais'].mean().reset_index().sort_values(by='Ganhos_Totais', ascending=False)

             Esporte  Ganhos_Totais
4            Futebol          557.0
1           Basquete          400.5
3               Boxe          373.5
7              Tenis          366.0
6              Golfe          334.0
0      Automobilismo          319.0
5  Futebol Americano          311.0
2           Beisebol          241.0

## Mediana

In [9]:
df['Ganhos_Totais'].median()

np.float64(354.0)

In [10]:
df.groupby('Esporte')['Ganhos_Totais'].median().reset_index().sort_values(by='Ganhos_Totais', ascending=False)

             Esporte  Ganhos_Totais
4            Futebol          565.0
1           Basquete          392.5
3               Boxe          373.5
7              Tenis          366.0
6              Golfe          334.0
5  Futebol Americano          329.0
0      Automobilismo          319.0
2           Beisebol          241.0

## Moda

In [11]:
df['Ganhos_Totais'].mode()

0    241
1    273
2    334
3    442
4    452
Name: Ganhos_Totais, dtype: int64

## Desvio Padrão

In [12]:
desvio_padrao = df.groupby('Esporte')['Ganhos_Totais'].std().reset_index()
desvio_padrao

             Esporte  Ganhos_Totais
0      Automobilismo            NaN
1           Basquete     103.414561
2           Beisebol            NaN
3               Boxe      96.873629
4            Futebol      86.278618
5  Futebol Americano      62.960305
6              Golfe            NaN
7              Tenis     107.480231

### Alguns registros estão NAN, isso ocorre quando temos apenas 1 registro para o esporte, pois não temos como calcular o desvio padrão se não temos mais de um registro

## Describe

In [13]:
df.describe()

       Ganhos_Totais
count      25.000000
mean      377.000000
std       110.029541
min       238.000000
25%       290.000000
50%       354.000000
75%       442.000000
max       639.000000