In [ ]:
install.packages ("readr")
install.packages ("readxl")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(readr)
library(readxl)

In [ ]:
dados <- read.csv("ESPORTISTAS_MOD7.csv", sep = ";")
head(dados)

  Atleta            Esporte  Ganhos_Totais
1 Lionel Messi      Futebol  639
2 Lebron James      Basquete 595
3 Cristiano Ronaldo Futebol  565
4 Neymar Jr         Futebol  467
5 Stephen Curry     Basquete 452
6 Kevin Duart       Basquete 452

## Média

In [ ]:
mean(dados$Ganhos_Totais)  # O operador $ é usado para acessar uma coluna específica em um dataframe.

[1] 377

In [ ]:
aggregate(Ganhos_Totais ~ Esporte, data = dados, FUN = mean)
# No puthon usamos groupby, no R usamos aggregate
# ~ especifica que queremos agrupar os dados por esporte e calcular a média por ganhos totais para cada grupo
# FUN = mean especifica que queremos calcular a média dos valores em  cada grupo

  Esporte           Ganhos_Totais
1 Automobilismo     319.0
2 Basquete          400.5
3 Beisebol          241.0
4 Boxe              373.5
5 Futebol           557.0
6 Futebol Americano 311.0
7 Golfe             334.0
8 Tenis             366.0

## Mediana

In [ ]:
median(dados$Ganhos_Totais)

[1] 354

In [ ]:
aggregate(Ganhos_Totais ~ Esporte, data = dados, FUN = median)

  Esporte           Ganhos_Totais
1 Automobilismo     319.0
2 Basquete          392.5
3 Beisebol          241.0
4 Boxe              373.5
5 Futebol           565.0
6 Futebol Americano 329.0
7 Golfe             334.0
8 Tenis             366.0

## Moda

In [ ]:
calcular_moda <- function(x){
  unique_x <- unique(x)  # unique() para obter os valores únicos do vetor.
  contagem <- tabulate(match(x, unique_x))  # tabulate() para cotar a frequencia de cada valor.
  moda <- unique_x[which.max(contagem)]  # which.max() para encontrar o índice do valor com a frequencia máxima.
  return(moda)
}
calcular_moda(dados$Ganhos_Totais)

[1] 452

## Desvio Padrão

In [ ]:
aggregate(Ganhos_Totais ~ Esporte, data = dados, FUN = sd)

  Esporte           Ganhos_Totais
1 Automobilismo            NA
2 Basquete          103.41456
3 Beisebol                 NA
4 Boxe               96.87363
5 Futebol            86.27862
6 Futebol Americano  62.96030
7 Golfe                    NA
8 Tenis             107.48023