# **MÓDULO 13**
# Projeto - Fundamentos da Descoberta de Dados

Nesse projeto trabalharemos com a base de dados de produtos de um supermercado do Chile.
A ideia é que vocês apliquem os conceitos estatísticos vistos no último módulo, mais os conceitos de visualizações de dados através de gráficos e finalizem publicando no seu github!

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

Faça a leitura dos dados do arquivo CSV:


Altere o código abaixo de acordo com seu diretório.

In [4]:
df = pd.read_csv("MODULO7_PROJETOFINAL_BASE_SUPERMERCADO.csv", delimiter=',')

df.head(10)

,title,Marca,Preco_Normal,Preco_Desconto,Preco_Anterior,Desconto,Categoria
0,"Pack 12 un, Leche extra proteína 1 L",Loncoleche,19788,0,0,0,lacteos
1,"Pack 12 un, Leche chocolate receta original 1 L",Soprole,18228,0,0,0,lacteos
2,"Pack 12 un, Leche semidescremada chocolate 1 L",Soprole,18228,0,0,0,lacteos
3,"Pack 12 un, Leche semidescremada frutilla 1 L",Soprole,18228,0,0,0,lacteos
4,"Pack 12 un, Leche sin lactosa chocolate 1 L",Loncoleche,17988,0,0,0,lacteos
5,"Pack 12 un, Leche sin lactosa frutilla 1 L",Loncoleche,17988,0,0,0,lacteos
6,"Pack 12 un, Leche saborizada light chocolate 1 L",Loncoleche,17988,0,0,0,lacteos
7,"Pack 12 un, Leche saborizada frutilla 1 L",Colun,17388,0,0,0,lacteos
8,"Pack 12 un, Leche saborizada vainilla 1 L",Colun,17388,0,0,0,lacteos
9,"Pack 12 un, Leche saborizada manjar 1 L",Colun,17388,0,0,0,lacteos

Os campos do nosso dataframe são:

**Title:** Nome do produto.


**Marca:** A marca do produto.


**Preco_Normal:** O preço em que o produto costuma ser vendido quando não há desconto.


**Preco_Desconto:** O preço vendido após o desconto ser aplicado.


**Preco_Anterior:** Preço em que era comercializado o produto antes do desconto aplicado.


**Desconto:** Total de desconto aplicado.






As colunas que aparecem com valores 0 são para os produtos onde não tivemos descontos aplicados.


As categorias estão em espanhol!

# 1 - Traga a média e a mediana dos preços - coluna Preco_Normal - por categoria de produto.
# Identifique as categorias que parecem ter um valor de média abaixo ou acima da mediana.

In [21]:
#Seu código aqui para a média
df.groupby('Categoria')['Preco_Normal'].mean().round(2).reset_index().sort_values(by='Preco_Normal', ascending=False)

                    Categoria  Preco_Normal
1          comidas-preparadas       3095.04
5                     lacteos       2385.22
2                  congelados       2108.04
0  belleza-y-cuidado-personal       1783.56
3                      frutas       1724.47
6                    verduras       1343.30
4        instantaneos-y-sopas        765.49

In [20]:
#Seu código aqui para a mediana
df.groupby('Categoria')['Preco_Normal'].median().round(2).reset_index().sort_values(by='Preco_Normal', ascending=True)

                    Categoria  Preco_Normal
4        instantaneos-y-sopas         439.0
5                     lacteos         989.0
6                    verduras        1180.0
3                      frutas        1195.0
2                  congelados        1519.0
0  belleza-y-cuidado-personal        1569.0
1          comidas-preparadas        3290.0

Digite aqui as categorias:

Acima da Mediana: belleza-y-cuidado-personal, congelados, frutas, verduras, lacteos e instantaneos-y-sopas

Abaixo da Mediana: comidas-preparadas

# 2 - Traga o desvio padrão por categoria de produto.
# Qual o comportamento da média e mediana nas categorias com maior desvio?

In [19]:
#Seu código aqui
df.groupby('Categoria')['Preco_Normal'].std().round(2).reset_index().sort_values(by='Preco_Normal', ascending=True)

                    Categoria  Preco_Normal
6                    verduras       1012.70
4        instantaneos-y-sopas       1170.23
3                      frutas       1639.15
1          comidas-preparadas       2019.91
2                  congelados       2111.54
0  belleza-y-cuidado-personal       2210.04
5                     lacteos       3925.82

Digite nesse campo o comportamento que você identificou:

Média >> Mediana → muitos valores altos (outliers)

Mediana >> Média → alguns valores muito baixos

# 3 - Plot um boxplot da distribuição do Preco_Normal para a categoria que você identificou que tem o maior desvio padrão. Como é a distribuição desses dados segundo o boxplot? Você identifica muitos outliers?

Dica: Para trazer apenas os dados da categoria que você deseja você pode usar o df.loc[df['Categoria'] == 'CATEGORIA ESCOLHIDA'

In [ ]:
# Seu código aqui
df_lacteos = df.loc[df['Categoria'] == 'lacteos']
fig = px.box(df_lacteos, y='Preco_Normal', title='BoxPlot - Lácteos')
fig.show()

A categoria lacteos é a categoria com mais produtos com preço acima da média, ou seja, outliers.

# 4 - Plote um gráfico de barras onde temos a média de descontos por categoria.

In [23]:
# Seu código aqui
desconto_categoria = df.groupby('Categoria')['Desconto'].mean().round(2).reset_index()

fig = px.bar(desconto_categoria, x='Desconto', y='Categoria', orientation='h', 
            title='Desconto por Categoria',
            labels={'Desconto': 'Desconto Médio', 'Categoria': 'Categoria'},
            color='Desconto', width=800)
fig.show()

# 5 - Plote um gráfico de mapa interativo agrupando os dados por categoria, marca e trazendo a média de desconto.

In [5]:
# Seu código aqui
categoria_marca_desconto = df.groupby(['Categoria', 'Marca'])['Desconto'].mean().round(2).reset_index()

fig = px.treemap(categoria_marca_desconto, path=['Categoria', 'Marca'],
                values='Desconto', title='Marcas por Categorias e Desconto Médio',
                color='Desconto')
fig.show()