# **MÓDULO 20 - Projeto de Credit Score - Naive Bayes**

No módulo 17 vocês realizaram a primeira etapa do projeto de crédito de vocês.
Então fizeram o tratamendo dos dados, balancearam as classes, transformaram as variáveis categóricas e separam base de treino e teste.
Nessa aula aplicaremos o algoritmo de naive bayes a base de vocês afim de tentarmos trazer previsões do score de crédito.

**IMPORTANTE:** Não se esqueçam de ao enviar o código de vocês para os tutores, enviarem as bases, pois como cada um de vocês realizou as alterações de tratamento indidualmente o tutor precisa ter acesso aos seus dados individuais.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

Durante a aula nossa variável a ser prevista (churn) continha apenas 2 categorias, a base de vocês contém mais. O Naive Bayes pode ser aplicado para problemas de classificação com múltiplas classes da mesma forma que para problemas de classificação binária. O Naive Bayes é um algoritmo de classificação probabilístico que calcula a probabilidade de uma amostra pertencer a cada classe e seleciona a classe com a maior probabilidade como a previsão final.
Em resumo, o Naive Bayes pode ser aplicado da mesma maneira para problemas de classificação com múltiplas classes, e os mesmos princípios se aplicam em termos de treinamento, avaliação e aplicação do modelo.

# 1) Comece carregando as bases de treino (X e y) e teste (X e y).
Verifique se o número de linhas condiz, se as variáveis estão corretas sendo apenas a de score para y e as demais nas bases de X e por último, se Y está balanceada no teste.

In [2]:
X_test = pd.read_csv("X_testt.csv", delimiter=',')
X_train_balanced = pd.read_csv("X_train_balancedd.csv", delimiter=',')
y_test = pd.read_csv("y_testt.csv", delimiter=',')
y_train_balanced = pd.read_csv("y_train_balancedd.csv", delimiter=',')

In [3]:
X_test

,Age,Income,Number of Children,Gender_encoded,Marital Status_encoded,Home Ownership_encoded,Education_Bachelor's Degree,Education_Doctorate,Education_High School Diploma,Education_Master's Degree
0,25,5500000.0,0,0,1,1,1,0,0,0
1,48,8750000.0,1,0,0,0,0,1,0,0
2,26,5500000.0,1,0,0,0,1,0,0,0
3,39,6250000.0,2,0,0,0,1,0,0,0
4,35,9000000.0,1,0,0,0,0,1,0,0
5,25,5500000.0,0,0,1,1,1,0,0,0
6,48,8250000.0,1,0,0,0,0,1,0,0
7,48,8250000.0,1,0,0,0,0,1,0,0
8,36,9500000.0,2,0,0,0,0,0,0,1
9,36,9500000.0,1,0,0,0,0,0,1,0
10,36,5000000.0,0,1,1,1,0,0,1,0
11,36,2750000.0,0,0,1,1,0,0,1,0
12,36,9500000.0,0,1,1,0,0,0,0,1
13,50,16000000.0,0,1,0,0,0,0,0,1
14,29,2500000.0,0,0,1,1,0,0,1,0
15,30,10500000.0,2,1,0,0,0,0,0,1
16,32,8500000.0,0,1,1,1,0,0,0,1
17,27,3750000.0,0,0,1,1,0,0,1,0
18,36,13000000.0,0,1,0,0,0,0,1,0
19,36,8500000.0,1,0,0,0,0,1,0,0
20,37,7500000.0,2,0,0,0,1,0,0,0
21,36,3000000.0,0,0,1,1,0,0,0,0
22,36,3500000.0,0,0,1,1,0,0,1,0
23,36,10500000.0,0,1,1,0,0,1,0,0
24,35,8000000.0,1,0,0,0,0,1,0,0
25,38,6750000.0,2,0,0,0,1,0,0,0
26,50,16250000.0,0,1,0,0,0,0,0,1
27,44,8750000.0,0,1,1,0,0,0,0,1
28,34,10500000.0,1,1,0,1,1,0,0,0
29,34,4750000.0,0,1,1,1,0,0,0,0
30,45,10500000.0,3,0,0,0,1,0,0,0
31,52,13500000.0,0,1,0,0,0,0,1,0
32,35,8500000.0,1,0,0,0,0,1,0,0
33,36,12500000.0,0,1,0,0,0,0,0,0
34,35,7500000.0,1,0,0,0,0,1,0,0
35,30,11750000.0,2,1,0,0,0,0,0,1
36,47,9000000.0,1,0,0,0,0,1,0,0
37,32,5750000.0,0,1,1,1,0,0,0,0
38,36,9000000.0,2,0,0,0,0,0,0,1
39,28,3250000.0,0,0,1,1,0,0,0,0
40,39,6000000.0,2,0,0,0,1,0,0,0

In [4]:
y_test

    Credit Score
0              0
1              1
2              0
3              1
4              1
5              0
6              1
7              1
8              1
9              1
10             0
11             2
12             1
13             1
14             2
15             1
16             1
17             2
18             1
19             1
20             1
21             2
22             2
23             1
24             1
25             1
26             1
27             1
28             1
29             0
30             1
31             1
32             1
33             1
34             1
35             1
36             1
37             0
38             1
39             2
40             1

In [5]:
X_train_balanced

,Age,Income,Number of Children,Gender_encoded,Marital Status_encoded,Home Ownership_encoded,Education_Bachelor's Degree,Education_Doctorate,Education_High School Diploma,Education_Master's Degree
0,26,4.500000e+06,0,0,1,1,0,0,0,0
1,29,2.750000e+06,0,0,1,1,0,0,1,0
2,25,6.250000e+06,0,0,1,1,1,0,0,0
3,29,6.800000e+06,2,0,0,0,0,1,0,0
4,31,6.500000e+06,0,1,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...
247,27,3.680365e+06,0,0,1,1,0,0,0,0
248,27,3.750000e+06,0,0,1,1,0,0,1,0
249,28,2.994626e+06,0,0,1,1,0,0,0,0
250,27,3.541294e+06,0,0,1,1,0,0,0,0
251,27,3.361054e+06,0,0,1,1,0,0,0,0

In [6]:
y_train_balanced

     Credit Score
0               0
1               2
2               0
3               0
4               0
..            ...
247             2
248             2
249             2
250             2
251             2

[252 rows x 1 columns]

# 2) Aplique o algoritmo de Naive Bayes aos dados de treinamento.

In [ ]:
#seu código aqui

# 3) Faça a avaliação do modelo com os dados de treinamento.
Traga a acurácia, recall e plote a matriz de confusão. Não se esqueça de avaliar com suas palavras o desempenho do modelo, interpretando as métricas.

Dica: Para calcularmos o recall em classificação multi classe precisamos usar o atributo macro:
recall = recall_score(y_train, y_pred_train, average='macro')

In [ ]:
#seu código aqui

# 4) Aplique o modelo aos dados de teste e realize a avaliação dos resultados, da mesma forma que fez acima. Não se esqueça de avaliar com as suas palavras e comparar o desempenho da base treino com a teste.

In [ ]:
#seu código aqui

# 5) Descreva com suas palavras o projeto desenvolvido nessa atividade e qual o nosso objetivo principal ao aplicarmos o algoritmo de naive bayes a base de crédito.
Utilize pelo menos 4 linhas.

Dica: Caso você ainda esteja tendo dificuldade em visualizar a aplicação dos projetos e objetivo, consulte seus tutores!